Exerci
https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [ ]:
# import numpy as np

In [10]:
#1.Import numpy as np and print the version number.

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
#2.Create a 3×3 numpy array of all True’s

arr2 = np.ones((3,3), dtype=bool)
print(arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [32]:
#3.Extract all odd numbers from arr

arr3 = np.arange(1,10,2)
print(arr3)

[1 3 5 7 9]


In [39]:
#4.Replace all odd numbers in arr with -1

arr4 = np.arange(1,10)
arr4[arr4%2==1] = -1   
print(arr4)

[-1  2 -1  4 -1  6 -1  8 -1]


In [59]:
#5.Replace all odd numbers in arr with -1 without changing arr

arr5 = np.arange(1,10)
out  = np.where(arr5%2==1,-1,arr5)

print('arr5=',arr5,'out=',out)

('arr5=', array([1, 2, 3, 4, 5, 6, 7, 8, 9]), 'out=', array([-1,  2, -1,  4, -1,  6, -1,  8, -1]))


In [81]:
#6.Convert a 1D array to a 2D array with 2 rows

arr6 = np.arange(0,10).reshape((2,5))
print(arr6)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [97]:
#7.Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#c = np.concatenate([a, b], axis=0)

c= np.r_[a, b]

print (c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [120]:
#8.Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

c = np.hstack([a,b])

d = np.c_[a,b]

print(c)
print(d)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [127]:
#9.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3])
a = np.r_[np.repeat(a, 3), np.tile(a, 3)]

print(a)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [129]:
#10.Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b)

print(c)

[2 4]


In [134]:
#11.From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a,b,True)

print(c)

[1 2 3 4]


In [170]:
#12.Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Monkey mode:
c = np.where(a == 2)
d = np.where(a == 4)
e = np.concatenate([c,d], axis= 1)

#correct:
f = np.where(a==b)

print(f)

(array([1, 3, 5, 7]),)


In [209]:
#13. Get all items between 5 and 10 from a.

a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.where((a >= 5)&(a <= 10))


#Humanmode
index = np.where((a >= 5) & (a <= 10))
a[index]


#monkeymode:
print(a[(a >= 5) & (a <= 10)])
 

[ 6  9 10]
[10 11 12 13 14 15 16 17 18 19 20]
